/**
 * Yalman Gaming — SEO helpers.
 *
 * Two jobs:
 *
 *  1. `pageMetadata()` — one place that knows how a page's `<title>`,
 *     description, canonical URL and Open Graph card are assembled, so no page
 *     has to remember to set `alternates.canonical` (which is the field most
 *     often forgotten, and the one that decides which URL Google keeps).
 *  2. JSON-LD builders. `localBusinessJsonLd()` already lives in `@/lib/site`
 *     next to the facts it serialises; everything here is structure rather than
 *     business fact, so it belongs with the SEO plumbing instead.
 *
 * Nothing in this file may state a claim Yalman Gaming has not confirmed. The
 * only figures it touches — the address, the phone number and the Google rating
 * — come from `@/lib/site`.
 */

import type { Metadata } from "next";
import {
  contact,
  ratings,
  siteConfig,
  storeAddress,
  businessHours,
} from "@/lib/site";

/* -------------------------------------------------------------------------- */
/* URLs                                                                       */
/* -------------------------------------------------------------------------- */

/** `siteConfig.url` without a trailing slash, so joins never double up. */
const ORIGIN = siteConfig.url.replace(/\/+$/, "");

/**
 * Absolute URL for a site-relative path. Passes an already-absolute URL
 * through untouched so callers can hand it either kind.
 */
export function absoluteUrl(path = "/"): string {
  if (/^https?:\/\//i.test(path)) return path;
  const clean = path.startsWith("/") ? path : `/${path}`;
  return clean === "/" ? ORIGIN : `${ORIGIN}${clean}`;
}

/**
 * The canonical form of a page URL: absolute, query string dropped.
 *
 * Filtered and paginated listings are deliberately *not* separate canonical
 * URLs — `/shop/graphics-cards?brand=asus&page=2` is the same page of the shop
 * viewed through a control panel, and pointing every combination at the base
 * category is what keeps the crawl budget on real pages.
 */
export function canonicalUrl(path = "/"): string {
  return absoluteUrl(path.split(/[?#]/)[0] || "/");
}

/* -------------------------------------------------------------------------- */
/* Metadata                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Search terms this store actually competes for. Individual pages add their
 * own; these ride along on every page built through `pageMetadata` so the
 * location signal is never missing.
 *
 * Keywords are a weak-to-worthless ranking signal on their own — the words that
 * matter are the ones in the visible copy. This list exists so the page's
 * subject is unambiguous to the crawlers that still read it, not as a
 * substitute for writing the page properly.
 */
export const CORE_KEYWORDS = [
  "gaming PC Lahore",
  "gaming computer Lahore",
  "gaming PC Pakistan",
  "custom PC Lahore",
  "PC builder Pakistan",
  "computer shop Hafeez Centre",
  "Yalman Gaming",
] as const;

/* -------------------------------------------------------------------------- */
/* Draft policy pages                                                         */
/* -------------------------------------------------------------------------- */

/**
 * Pages that exist as *templates* rather than published policy.
 *
 * Yalman Gaming has not supplied warranty, returns, shipping, privacy or terms
 * text, so those five pages render their real structure with every unconfirmed
 * clause visibly marked. They are reachable, linked from the footer and useful
 * to a customer who lands on them — but they must not be the result Google
 * shows for "gaming PC warranty Lahore", because a search snippet strips the
 * "still being finalised" banner that makes the page honest.
 *
 * This one array is the switch. `pageMetadata` reads it to emit `noindex`, and
 * `src/app/sitemap.ts` reads it to leave the same URLs out — a sitemap listing
 * a noindexed page is a contradictory signal. **Delete a path from here when
 * its terms are real** and the page becomes indexable and appears in the
 * sitemap in the same commit.
 */
export const DRAFT_POLICY_PATHS = [
  "/warranty",
  "/returns",
  "/shipping",
  "/privacy",
  "/terms",
] as const;

/** True when `path` is one of the unpublished policy templates. */
export function isDraftPolicyPath(path: string): boolean {
  const clean = (path.split(/[?#]/)[0] || "/").replace(/\/+$/, "") || "/";
  return (DRAFT_POLICY_PATHS as readonly string[]).includes(clean);
}

/**
 * The site-wide Open Graph card, generated by `src/app/opengraph-image.tsx`.
 *
 * Next's file convention normally injects this automatically — but only into a
 * page that has *not* declared `openGraph` itself. Every page built through
 * `pageMetadata` does declare one (it has to, for the canonical URL and the
 * site name), which replaces the convention's object wholesale and silently
 * drops the image with it. Naming the route here is what puts it back.
 *
 * The generated URL carries a content hash as a cache-busting query string
 * (`/opengraph-image?a1b2c3`). That hash is not knowable from here, so this
 * points at the unhashed route, which serves the same image. The trade is that
 * a scraper which cached the old card will keep it until its own cache expires
 * — worth it to have a card at all.
 */
const DEFAULT_OG_IMAGE = "/opengraph-image";
const OG_IMAGE_SIZE = { width: 1200, height: 630 } as const;

export type PageMetadataInput = {
  /** Bare page title. The root layout appends "| Yalman Gaming". */
  title: string;
  description: string;
  /** Site-relative path, e.g. `/showcase`. Becomes the canonical URL. */
  path: string;
  /** Site-relative or absolute image URL. Defaults to the site OG card. */
  image?: string;
  /** Extra search terms for this page, merged with `CORE_KEYWORDS`. */
  keywords?: string[];
  /**
   * Keep the page out of the index (thank-you pages, private views). A path in
   * `DRAFT_POLICY_PATHS` is noindexed whether or not this is set.
   */
  noIndex?: boolean;
  type?: "website" | "article";
};

/**
 * Builds a complete `Metadata` object for a content page.
 *
 * `openGraph` is emitted in full rather than partially: Next replaces — never
 * merges — a parent's `openGraph` when a child defines one, so a partial object
 * here would silently drop the site name and locale set in the root layout.
 */
export function pageMetadata({
  title,
  description,
  path,
  image,
  keywords,
  noIndex = false,
  type = "website",
}: PageMetadataInput): Metadata {
  const url = canonicalUrl(path);
  const ogImage = absoluteUrl(image ?? DEFAULT_OG_IMAGE);
  const fullTitle = `${title} | ${siteConfig.name}`;
  // A draft policy page is noindexed regardless of what the caller passed, so
  // no page can forget. See `DRAFT_POLICY_PATHS`.
  const hidden = noIndex || isDraftPolicyPath(path);

  return {
    title,
    description,
    keywords: [...CORE_KEYWORDS, ...(keywords ?? [])],
    alternates: { canonical: url },
    openGraph: {
      type,
      url,
      title: fullTitle,
      description,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      images: [
        {
          url: ogImage,
          width: OG_IMAGE_SIZE.width,
          height: OG_IMAGE_SIZE.height,
          alt: fullTitle,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [ogImage],
    },
    ...(hidden
      ? {
          // `follow` stays on: the page is a genuine part of the site and its
          // links to /contact and /builder should still carry weight. Only the
          // draft text itself is kept out of the index.
          robots: { index: false, follow: true, googleBot: { index: false, follow: true } },
        }
      : {}),
  };
}

/* -------------------------------------------------------------------------- */
/* JSON-LD                                                                    */
/* -------------------------------------------------------------------------- */

/** Anything JSON-serialisable that can be handed to a `<script type="application/ld+json">`. */
export type JsonLdObject = Record<string, unknown>;

/**
 * The store as an organisation, for the knowledge panel and for `publisher`
 * references from other structured data.
 *
 * No `logo` is emitted: Google requires a real, fetchable image and the site
 * ships no logo asset yet. An organisation without a logo is valid; one
 * pointing at a 404 is worse than none.
 */
export function organizationJsonLd(): JsonLdObject {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${ORIGIN}/#organization`,
    name: siteConfig.name,
    legalName: siteConfig.legalName,
    url: ORIGIN,
    description: siteConfig.description,
    telephone: `+${contact.phoneE164}`,
    address: {
      "@type": "PostalAddress",
      streetAddress: `${storeAddress.floor}, ${storeAddress.building}, ${storeAddress.shop}`,
      addressLocality: storeAddress.city,
      addressRegion: "Punjab",
      postalCode: storeAddress.postalCode,
      addressCountry: storeAddress.countryCode,
    },
    contactPoint: [
      {
        "@type": "ContactPoint",
        telephone: `+${contact.phoneE164}`,
        contactType: "customer service",
        areaServed: "PK",
        availableLanguage: ["en", "ur"],
      },
    ],
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: ratings.google.score,
      reviewCount: ratings.google.count,
      bestRating: 5,
    },
    sameAs: [siteConfig.existingSite],
  };
}

/**
 * Site-level entry with a search action, so a site-links search box points at
 * the real shop search rather than a guessed URL.
 */
export function websiteJsonLd(): JsonLdObject {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${ORIGIN}/#website`,
    url: ORIGIN,
    name: siteConfig.name,
    description: siteConfig.description,
    inLanguage: "en-PK",
    publisher: { "@id": `${ORIGIN}/#organization` },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${ORIGIN}/shop?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  };
}

/**
 * Breadcrumb trail.
 *
 * Takes the same `{ label, href }` shape as `@/components/shop/Breadcrumbs`,
 * so a page can feed one array to both the visible trail and the markup and
 * they can never describe different paths.
 */
export function breadcrumbJsonLd(
  items: { label: string; href?: string }[],
): JsonLdObject {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.label,
      ...(item.href ? { item: absoluteUrl(item.href) } : {}),
    })),
  };
}

export type FaqEntry = { question: string; answer: string };

/**
 * FAQ markup.
 *
 * Only ever call this with questions that are answered *in the visible copy* of
 * the same page — Google treats hidden-only FAQ markup as spam, and more to the
 * point, an answer nobody can read on the page is an answer nobody agreed to.
 */
export function faqJsonLd(entries: FaqEntry[]): JsonLdObject {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: entries.map((entry) => ({
      "@type": "Question",
      name: entry.question,
      acceptedAnswer: { "@type": "Answer", text: entry.answer },
    })),
  };
}

export type ItemListEntry = {
  name: string;
  /** Site-relative path to the item's own page. */
  path: string;
  description?: string;
  image?: string;
};

/** Ordered list of pages — used by the showcase index and category listings. */
export function itemListJsonLd({
  name,
  description,
  items,
}: {
  name: string;
  description?: string;
  items: ItemListEntry[];
}): JsonLdObject {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    ...(description ? { description } : {}),
    numberOfItems: items.length,
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      url: absoluteUrl(item.path),
      ...(item.description ? { description: item.description } : {}),
      ...(item.image ? { image: absoluteUrl(item.image) } : {}),
    })),
  };
}

/**
 * A single content page (about, assembly, a policy page).
 *
 * `ContactPage` and `AboutPage` are distinct types in schema.org and Google
 * reads them differently, so the caller picks.
 */
export function webPageJsonLd({
  type = "WebPage",
  name,
  description,
  path,
}: {
  type?: "WebPage" | "AboutPage" | "ContactPage";
  name: string;
  description: string;
  path: string;
}): JsonLdObject {
  return {
    "@context": "https://schema.org",
    "@type": type,
    name,
    description,
    url: canonicalUrl(path),
    inLanguage: "en-PK",
    isPartOf: { "@id": `${ORIGIN}/#website` },
    publisher: { "@id": `${ORIGIN}/#organization` },
  };
}

/**
 * The store's opening hours as structured data.
 *
 * Only the closing time was supplied by the owner, and `OpeningHoursSpecification`
 * requires both ends of the interval — so this emits `closes` alone rather than
 * inventing an opening time. Consumers that need both will ignore it, which is
 * the correct outcome.
 */
export function openingHoursJsonLd(): JsonLdObject {
  return {
    "@type": "OpeningHoursSpecification",
    dayOfWeek: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    closes: businessHours.closingTime24,
  };
}
